#define crno_polje 177
#define bijelo_polje 178
#define crna_figura ' ' //bolje koristiti prazan space radi ispisa jer karakter 170 ASCII vrijednosti je -> " ¬ "
#define bijela_figura 219
#define duzina 8
#define sirina duzina*2
char SahovskeFigure[26][duzina][sirina] = {

   {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

     {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

     {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

      {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

     {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

     {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

     {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

     {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

     {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},

    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},
    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},
    {{bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijelo_polje,bijelo_polje},
                    {bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje,bijelo_polje}},
   {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,bijela_figura,bijela_figura,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,bijela_figura,bijela_figura,crno_polje,crno_polje},
                    {crno_polje,crno_polje,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,bijela_figura,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},
    {{crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crna_figura,crna_figura,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crna_figura,crna_figura,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crna_figura,crno_polje,crno_polje},
                    {crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje,crno_polje}},

};
